ignore:
    - "mocks/"
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        informational: true
    patch:
      default:
        informational: true