package gphotos

import (
	"log"
	"os"
)

const (
	// Prefix to write at beginning of each log line.
	logPrefix = ""

	// Define which text to prefix to each log entry generated by the Logger.
	// For example, flags Ldate | Ltime (or LstdFlags) produce,
	//	2009/01/23 01:23:23 message
	// while flags Ldate | Ltime | Lmicroseconds | Llongfile produce,
	//	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
	//
	// See standard `log` package.
	logFlags = 0
)

func defaultLogger() *log.Logger {
	return log.New(os.Stdout, logPrefix, logFlags)
}
